import {analyze,adminToken,saveApiKey,apiKey,authorize,bucket,database,identity,reject,reply,textValue,type Frame,type Item} from '@/lib/server';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const user=await identity(),d=database();const spaces=user==='creator'?(await d.prepare('SELECT * FROM spaces WHERE owner=? ORDER BY created DESC').bind(user).all()).results:(await d.prepare('SELECT * FROM spaces WHERE id=?').bind(user.slice(7)).all()).results;const space=new URL(request.url).searchParams.get('space');let captures:any[]=[],members=0,invite='',feedback:any[]=[];if(space){const s=await authorize(space,user);invite=s.owner===user?s.invite:'';captures=(await d.prepare('SELECT * FROM captures WHERE space=? ORDER BY created DESC LIMIT 50').bind(space).all()).results.map((c:any)=>({...c,frames:JSON.parse(c.frames),objects:JSON.parse(c.objects),canDelete:c.owner===user,owner:undefined}));members=Number((await d.prepare('SELECT COUNT(*) AS n FROM members WHERE space=?').bind(space).first<any>())?.n||0);feedback=(await d.prepare('SELECT found,intent,seconds,created FROM feedback WHERE space=? ORDER BY created DESC LIMIT 50').bind(space).all()).results;}
 const budget=await d.prepare('SELECT COALESCE(SUM(cost),0) AS total,SUM(CASE WHEN status!=? THEN 1 ELSE 0 END) AS unconfirmed FROM ledger').bind('completed').first();return reply({spaces:spaces.map((s:any)=>({id:s.id,name:s.name,isOwner:s.owner===user})),captures,members,invite,feedback,budget,aiReady:!!(await apiKey())});}catch(e){return reject(e);}}
export async function POST(request:Request){try{
 const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return reply({error:'操作元を確認できませんでした。'},403);
 const d=database();if(Number(request.headers.get('content-length')||0)>3_500_000)throw new Error('データが大きすぎます。画像数を減らしてください。');const raw=await request.text();if(raw.length>3_500_000)throw new Error('データが大きすぎます。');const b=JSON.parse(raw);const action=b.action;
 if(action==='logout')return new Response('{}',{headers:{'Content-Type':'application/json','Set-Cookie':'arika_access=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0','Cache-Control':'no-store'}});
 if(action==='login'){
 const token=textValue(b.token,200);let owner=false;
 if(adminToken()&&token===adminToken()){owner=true;const existing=await d.prepare("SELECT id FROM spaces WHERE owner='creator'").first<any>();if(!existing){await d.batch([d.prepare('INSERT INTO spaces(id,name,owner,invite,created) VALUES(?,?,?,?,?)').bind('shared-space','共有スペース','creator',crypto.randomUUID().replaceAll('-',''),new Date().toISOString()),d.prepare('INSERT INTO members(space,user) VALUES(?,?)').bind('shared-space','creator'),d.prepare("INSERT OR IGNORE INTO config(key,value) VALUES('admin','creator')")]);}}
 else {const s=await d.prepare('SELECT id FROM spaces WHERE invite=?').bind(token).first();if(!s)throw new Error('招待リンクを確認してください。');}
 return new Response(JSON.stringify({ok:true,owner}),{headers:{'Content-Type':'application/json','Set-Cookie':`arika_access=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`,'Cache-Control':'no-store'}});
 }
 const user=await identity();
 if(action==='setkey'){if(user!=='creator')throw new Error('作成者のみ設定できます。');const key=textValue(b.key,500);if(!key.startsWith('sk-')||key.length<20)throw new Error('OpenAIのAPIキーを入力してください。');await saveApiKey(key);return reply({ok:true});}
 if(action==='create'||action==='join')throw new Error('招待リンクから共有スペースを開いてください。');
 const space=textValue(b.space,80);const s=await authorize(space,user);
 if(['save','delete','rotate','edit'].includes(action)&&s.owner!==user)throw new Error('記録の追加・変更・削除は作成者のみ利用できます。');
 if(action==='analyze'&&!textValue(b.query)&&s.owner!==user)throw new Error('初回解析は作成者のみ利用できます。');
 if(action==='edit'){const id=textValue(b.capture,80),label=textValue(b.label,80),notes=textValue(b.notes,500);if(!label)throw new Error('撮影場所を入力してください。');const c=await d.prepare('SELECT objects FROM captures WHERE id=? AND space=? AND owner=?').bind(id,space,user).first<any>();if(!c)throw new Error('記録が見つかりません。');const objects=JSON.parse(c.objects).filter((o:Item)=>o.source!=='手動');if(notes)objects.unshift({name:notes,description:'撮影者のメモ',location:label,frame:0,source:'手動'});await d.prepare('UPDATE captures SET label=?,objects=? WHERE id=?').bind(label,JSON.stringify(objects),id).run();return reply({ok:true});}
 if(action==='rotate'){if(s.owner!==user)throw new Error('作成者のみ操作できます。');await d.prepare('UPDATE spaces SET invite=? WHERE id=?').bind(crypto.randomUUID().replaceAll('-',''),space).run();return reply({ok:true});}
 if(action==='save'){
 const capturedAt=b.capturedAt?new Date(b.capturedAt):new Date();if(!Number.isFinite(capturedAt.getTime())||capturedAt.getTime()>Date.now()+600000||capturedAt.getFullYear()<1900)throw new Error('撮影日時を確認してください。');const label=textValue(b.label,80);if(!label)throw new Error('撮影場所を入力してください。');if(!Array.isArray(b.frames)||b.frames.length<1||b.frames.length>12)throw new Error('画像を1〜12枚選んでください。');const n=await d.prepare('SELECT COUNT(*) AS n FROM captures WHERE space=?').bind(space).first<any>();if(n.n>=30)throw new Error('記録は30件までです。不要な記録を削除してください。');
 const prepared=b.frames.map((f:any)=>{if(typeof f.data!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(f.data)||f.data.length>280000)throw new Error('画像を読み込めません。JPEG画像を小さくして再試行してください。');const binary=atob(f.data.split(',')[1]);const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));if(bytes[0]!==255||bytes[1]!==216)throw new Error('JPEG画像を選択してください。');return {bytes,time:typeof f.time==='number'&&Number.isFinite(f.time)?Math.max(0,f.time):0};});
 const id=crypto.randomUUID(),frames:Frame[]=[];try{for(const f of prepared){const key=space+'/'+id+'/'+crypto.randomUUID()+'.jpg';await bucket().put(key,f.bytes,{httpMetadata:{contentType:'image/jpeg'}});frames.push({id:key,time:f.time});}const notes=textValue(b.notes,500);const objects:Item[]=notes?[{name:notes,description:'撮影者が入力したメモ',location:label,frame:0,source:'手動'}]:[];await d.prepare('INSERT INTO captures(id,space,owner,label,created,frames,objects,mode) VALUES(?,?,?,?,?,?,?,?)').bind(id,space,user,label,capturedAt.toISOString(),JSON.stringify(frames),JSON.stringify(objects),'manual').run();return reply({id});}catch(e){for(const f of frames)await bucket().delete(f.id);throw e;}
 }
 if(action==='analyze'||action==='delete'){
 const capture=await d.prepare('SELECT * FROM captures WHERE id=? AND space=?').bind(textValue(b.capture,80),space).first<any>();if(!capture)throw new Error('記録が見つかりません。');if(action==='delete'){if(capture.owner!==user)throw new Error('削除できるのは撮影者のみです。');await d.prepare('DELETE FROM captures WHERE id=?').bind(capture.id).run();for(const f of JSON.parse(capture.frames))await bucket().delete(f.id);return reply({ok:true});}
 const q=textValue(b.query,180);const result=await analyze(space,JSON.parse(capture.frames),q);if(!q){const manual=JSON.parse(capture.objects).filter((x:Item)=>x.source==='手動');await d.prepare('UPDATE captures SET objects=?,mode=? WHERE id=?').bind(JSON.stringify([...manual,...result.objects]),'ai',capture.id).run();}return reply({...result,capture: capture.id});
 }
 if(action==='search'){const q=textValue(b.query,180);if(!q)throw new Error('探したいモノを入力してください。');const rows=(await d.prepare('SELECT * FROM captures WHERE space=? ORDER BY created DESC LIMIT 50').bind(space).all()).results;const normalize=(t:string)=>t.normalize('NFKC').toLowerCase();const groups=[['いす','椅子','イス','チェア','chair'],['つくえ','机','テーブル','table','desk'],['マイク','microphone'],['本','書籍','book'],['ケーブル','コード','cable']];const query=normalize(q);let terms=query.split(/[\s、。]+/).filter(Boolean);for(const g of groups)if(g.some(t=>query.includes(t)))terms.push(...g);terms=terms.map(t=>t.replace(/(はどこ.*|を探.*|ありますか.*|どこ.*|ですか.*)$/,'')).filter(Boolean);const results:any[]=[];for(const c of rows as any[]){const frames=JSON.parse(c.frames);for(const o of JSON.parse(c.objects)){const hay=normalize([o.name,o.description,o.location,c.label].join(' '));const score=terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0);if(score)results.push({...o,capture:c.id,label:c.label,created:c.created,image:frames[o.frame]?.id,time:frames[o.frame]?.time,score});}}results.sort((a,b)=>b.score-a.score);return reply({results:results.slice(0,30),cost:0,mode:'保存済み記録の検索'});}
 if(action==='feedback'){await d.prepare('INSERT INTO feedback(id,space,user,found,intent,seconds,created) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),space,user,b.found?1:0,textValue(b.intent,160),typeof b.seconds==='number'&&Number.isFinite(b.seconds)?Math.min(86400,Math.max(0,b.seconds)):0,new Date().toISOString()).run();return reply({ok:true});}
 throw new Error('操作を確認できませんでした。');
 }catch(e){return reject(e);}}
